### ISSUE TITLE
Risque de sécurité

### ISSUE THREAD

**Issue by 1000i100** [jytou/vanitygen#2]
Mettons que je cherche une clef publique avec comme motif : 
`^(toto|TOTO|Toto)`
Je trouve une clef qui commence par Toto.

Quelqu'un constate que ma clef publique commence par une séquence qui à peu de chance d'être le fruit du hasard et utilise vanitygen pour chercher : 
`^Toto`
La recherche se fait-elle dans un ordre déterministe ?
Dans quel cas la clef publique qu'il trouvera sera vraisemblablement la même que celle que j'ai trouvé, et il aura donc également la même clef privé à disposition.

Bref, l'ordre de recherche est-il déterministe ?

**Comment by 1000i100** [comment]
Testé, non déterministe, tout va bien ;)

**Comment by jytou** [comment]
Pour la petite histoire, l'initialisation aléatoire du random est faite en ligne 4793 :
>srand(time(NULL))
